#kubectl run pod1 --image=httpd:2.4.41-alpine  --namespace=default --dry-run=client -o yaml > pod1.yml
#create the nodeselector and tolerations as per documentation
#you can use 'kubectl describe nodes cluster1-master1 | grep -i taint' and 'kubectl get nodes --show-labels' to get the info you need
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
  namespace: default
spec:
  containers:
  - image: httpd:2.4.41-alpine
    name: pod1-container
    resources: {}
  nodeSelector:
    kubernetes.io/hostname: cluster1-master1
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
