#https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes
#pretty straigtforward just follow the documentation
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ready-if-service-ready
  name: ready-if-service-ready
spec:
  containers:
  - image: nginx:1.16.1-alpine
    name: ready-if-service-ready
    resources: {}
    livenessProbe:
        exec:
          command:
          - "/bin/true"
    readinessProbe:
      exec:
        command:
        - "sh"
        - "-c"
        - "wget -T2 -O- http://service-am-i-ready:80"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
